version: '3'

services:

  blog_project_db:
    image: postgres:latest
    container_name: blog_project_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  blog-app:
    image: blog:0.0.1-SNAPSHOT
    container_name: blog-app
    build:
      context: .
      dockerfile: DockerFile
    environment:
      SPRING_DATASOURCE_URL: ${POSTGRES_DB}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - blog_project_db
    ports:
      - 8080:8080

volumes:
  db-data:
    driver: local