spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/blog_project_db
    driver-class-name: org.postgresql.Driver
    username: <username>
    password: <password>

  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    enabled: true
    prefix: classpath:/templates/
    suffix: .html

flyway:
  check-location: false
  url: jdbc:postgresql://localhost:5432/blog_project_db
  locations: classpath:db/migration
  schemas: public
  init-version: 1 # version to start migration
  sql-migration-prefix: V
  sql-migration-suffix: .sql
  enabled: true
  user: <username>
  password: <password>
